name-template: '{{version}}'
tag-template: '{{version}}'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: 'Documentation'
    labels:
      - 'docs'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  {{#each categories}}
  {{#hasItems commits}}
  ### {{title}}

  {{#each commits}}
  - {{formatCommitMessage subject}}
  {{/each}}

  {{/hasItems}}
  {{/each}}